name: foleycrafter
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11.10
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - pip
  - pip:
    - diffusers==0.32.0.dev0
    - transformers==4.46.1
    - xformers
    - imageio==2.36.0
    - decord==0.6.0
    - einops==0.8.0
    - omegaconf
    - safetensors==0.4.5
    - gradio==5.5.0
    - tqdm==4.66.6
    - soundfile==0.12.1
    - wandb
    - moviepy==1.0.3
    - kornia==0.7.3
    - h5py==3.12.1
    - bitsandbytes
    - accelerate
    - flash-attn